# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: ProofIndexer
networks:
- id: 84532
  start_block: 0
  contracts:
  - name: ProofSchemaHook
    address:
    - 0xBF8a9A7769018B47E5C7b4df440917f930b32Eee
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
    - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
    - event: AttestationId(uint64 indexed attestationId)
    - event: AttestationNFTGiven(address indexed recipient, string uri)
    - event: BatchMetadataUpdate(uint256 _fromTokenId, uint256 _toTokenId)
    - event: MetadataUpdate(uint256 _tokenId)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: SetCompany(address indexed attester, string name)
    - event: SetInstitution(address indexed attester, string name)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - "hash"
    - "transactionIndex"